test_that("guided journey completes checkpoints in order and reaches the debrief", {
  old <- setwd(root)
  on.exit(setwd(old), add = TRUE)
  library(shiny)
  shiny::testServer(app_server, {
    checkpoint_inputs <- function(n) session$setInputs(suspect = "Still open", confidence = "Low",
      supporting = "Illness after event", against = "Recall errors", change = "Lab evidence", action_now = "Advise guests", checkpoint = n)
    expect_equal(guide_step(), 1L)
    session$setInputs(begin = 1)
    expect_equal(guide_step(), 2L)
    session$setInputs(suspect = "", supporting = "", checkpoint = 1)
    expect_equal(guide_step(), 2L)
    expect_length(s()$checkpoints, 0)
    checkpoint_inputs(2)
    expect_equal(guide_step(), 3L)
    expect_equal(s()$checkpoints[[1]]$stage, "After initial assessment")
    session$setInputs(character = "organizer", topic = "auto", question = "menu and walk-ins", ask = 1)
    expect_true(s()$menu)
    session$setInputs(interviews_done = 1)
    expect_equal(guide_step(), 4L)
    checkpoint_inputs(3)
    expect_equal(guide_step(), 5L)
    session$setInputs(person = "all", clinical = "standard", start = 0, end = 72, lab = FALSE,
      definition_reason = "Initial working definition", save_definition = 1)
    expect_equal(guide_step(), 6L)
    # The learner can request and receive the list without opening task tools.
    session$setInputs(prepare_list = 1)
    expect_false("guest_list" %in% s()$completed)
    session$setInputs(prepare_list = 2)
    expect_true("guest_list" %in% s()$completed)
    session$setInputs(audience = "all", domains = c("symptoms", "onset"), foods = names(food_labels(s()$sc)), send_team = 1)
    expect_equal(guide_step(), 6L)
    expect_equal(nrow(s()$collected), 0)
    session$setInputs(collection_done = 1)
    expect_equal(guide_step(), 7L)
    expect_equal(nrow(s()$collected), 60)
    session$setInputs(freeze = 1)
    expect_equal(nrow(snapshot()$data), 60)
    session$setInputs(analysis_done = 1)
    expect_equal(guide_step(), 8L)
    checkpoint_inputs(4)
    expect_equal(guide_step(), 9L)
    expect_equal(vapply(s()$checkpoints, `[[`, character(1), "stage"), c("After initial assessment", "After interviews", "After analysis"))
    session$setInputs(recommendation = "Suspected food exposure; advise guests while awaiting corroboration.", finish = 1)
    expect_equal(guide_step(), 10L)
    expect_match(output$debrief$html, "A profile, not a score", fixed = TRUE)
    session$setInputs(retry_checkpoint = "1", retry_reason = "I was unsure", retry_text = "Preserve samples now", save_retry = 1)
    expect_equal(s()$retry$revision, "Preserve samples now")
    session$setInputs(reveal = 1)
    expect_match(output$truth_reveal$html, "Simulated vehicle", fixed = TRUE)
  })
})

test_that("navigation preserves checkpoint drafts and never advances time", {
  old <- setwd(root)
  on.exit(setwd(old), add = TRUE)
  library(shiny)
  shiny::testServer(app_server, {
    session$setInputs(begin = 1, suspect = "Something at the event", supporting = "Several callers")
    session$setInputs(back_step = 1)
    expect_equal(guide_step(), 1L)
    expect_equal(checkpoint_drafts()[["2"]]$suspect, "Something at the event")
    session$setInputs(begin = 2)
    expect_equal(guide_step(), 2L)
    expect_equal(s()$clock, 0)
    expect_length(s()$checkpoints, 0)
    session$setInputs(revisit = "10", go_revisit = 1)
    expect_equal(guide_step(), 2L)
    session$setInputs(collection_done = 1)
    expect_equal(guide_step(), 2L)
    session$setInputs(revisit = "1", go_revisit = 2)
    expect_equal(guide_step(), 1L)
  })
})
